/** Complete GET /settings document matching Listmonk v6.2's models.Settings JSON shape. */
export function createListmonkV62SettingsFixture(): Record<string, unknown> {
	return {
		'app.site_name': 'YAH mail',
		'app.root_url': 'https://mail.example.test',
		'app.logo_url': '',
		'app.favicon_url': '',
		'app.from_email': 'YAH <hello@example.test>',
		'app.notify_emails': ['operator@example.test'],
		'app.enable_public_subscription_page': true,
		'app.enable_public_archive': false,
		'app.enable_public_archive_rss_content': false,
		'app.show_optin_page': true,
		'app.send_optin_confirmation': true,
		'app.check_updates': true,
		'app.lang': 'en',
		'app.batch_size': 1_000,
		'app.concurrency': 2,
		'app.max_send_errors': 1_000,
		'app.message_rate': 10,
		'app.cache_slow_queries': false,
		'app.cache_slow_queries_interval': '0 0 * * *',
		'app.message_sliding_window': false,
		'app.message_sliding_window_duration': '1m',
		'app.message_sliding_window_rate': 0,

		'privacy.individual_tracking': true,
		'privacy.disable_tracking': false,
		'privacy.unsubscribe_header': true,
		'privacy.allow_blocklist': true,
		'privacy.allow_preferences': true,
		'privacy.allow_export': true,
		'privacy.allow_wipe': true,
		'privacy.exportable': ['profile', 'subscriptions', 'campaign_views', 'link_clicks'],
		'privacy.record_optin_ip': false,
		'privacy.domain_blocklist': ['blocked.example'],
		'privacy.domain_allowlist': [],

		'security.captcha': {
			altcha: { enabled: false, complexity: 10_000 },
			hcaptcha: { enabled: false, key: '', secret: '••••••' },
		},
		'security.oidc': {
			enabled: false,
			provider_url: '',
			provider_name: '',
			client_id: '',
			client_secret: '••••••',
			auto_create_users: false,
			default_user_role_id: null,
			default_list_role_id: 2,
		},
		'security.trusted_urls': ['https://admin.example.test'],

		'upload.provider': 'filesystem',
		'upload.extensions': ['jpg', 'png'],
		'upload.filesystem.upload_path': 'uploads',
		'upload.filesystem.upload_uri': '/uploads',
		'upload.s3.url': '',
		'upload.s3.public_url': '',
		'upload.s3.aws_access_key_id': '',
		'upload.s3.aws_default_region': '',
		'upload.s3.aws_secret_access_key': '••••••',
		'upload.s3.bucket': '',
		'upload.s3.bucket_domain': '',
		'upload.s3.bucket_path': '',
		'upload.s3.bucket_type': '',
		'upload.s3.expiry': '24h',

		smtp: [{
			name: 'email-primary',
			uuid: '10000000-0000-4000-8000-000000000001',
			enabled: true,
			host: 'smtp.example.test',
			hello_hostname: '',
			port: 587,
			auth_protocol: 'login',
			username: 'mailer',
			password: '••••••••',
			email_headers: [{ 'X-Provider': 'keep-me' }],
			max_conns: 10,
			max_msg_retries: 2,
			msg_retry_delay: '10ms',
			idle_timeout: '15s',
			wait_timeout: '5s',
			tls_type: 'STARTTLS',
			tls_skip_verify: false,
			from_addresses: ['example.test'],
		}],
		messengers: [{
			uuid: '20000000-0000-4000-8000-000000000002',
			enabled: false,
			name: 'postback',
			root_url: 'https://postback.example.test',
			username: 'postback-user',
			password: '••••',
			max_conns: 2,
			timeout: '10s',
			max_msg_retries: 2,
		}],

		'bounce.enabled': true,
		'bounce.webhooks_enabled': true,
		'bounce.actions': {
			complaint: { count: 1, action: 'blocklist' },
			hard: { count: 1, action: 'blocklist' },
			soft: { count: 3, action: 'none' },
		},
		'bounce.ses_enabled': false,
		'bounce.sendgrid_enabled': false,
		'bounce.sendgrid_key': '••••',
		'bounce.azure': { enabled: false, shared_secret: '••••', shared_secret_header: 'x-bounce-secret' },
		'bounce.postmark': { enabled: false, username: '', password: '••••' },
		'bounce.forwardemail': { enabled: false, key: '••••' },
		'bounce.lettermint': { enabled: false, key: '••••' },
		'bounce.mailboxes': [{
			uuid: '30000000-0000-4000-8000-000000000003',
			enabled: false,
			type: 'pop',
			host: 'pop.example.test',
			port: 995,
			auth_protocol: 'userpass',
			return_path: 'bounce@example.test',
			username: 'bounce',
			password: '••••••',
			tls_enabled: true,
			tls_skip_verify: false,
			scan_interval: '15m',
		}],

		'maintenance.db': { vacuum: true, vacuum_cron_interval: '0 3 * * *' },
		'appearance.admin.custom_css': '',
		'appearance.admin.custom_js': '',
		'appearance.public.custom_css': '',
		'appearance.public.custom_js': '',
	};
}
