// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(app)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)")>;
    },
    {
      path: "/(auth)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)")>;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/emails";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/index")>;
      $$route?: undefined;
    },
    {
      path: "/(auth)/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/forgot-password")>;
      $$route?: undefined;
    },
    {
      path: "/(auth)/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/login")>;
      $$route?: undefined;
    },
    {
      path: "/(auth)/reset-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/reset-password")>;
      $$route?: undefined;
    },
    {
      path: "/api/adapter-probe";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/adapter-probe")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/adapter-probe")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/adapter-probe")>;
      $$route?: undefined;
    },
    {
      path: "/api/health";
      page: false;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/health")>;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/health")>;
      $$route?: undefined;
    },
    {
      path: "/compatibility/auth";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/auth")>;
      $$route?: undefined;
    },
    {
      path: "/compatibility/content";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/content")>;
      $$route?: undefined;
    },
    {
      path: "/compatibility/icons";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/icons")>;
      $$route?: undefined;
    },
    {
      path: "/compatibility/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/compatibility/index")>;
    },
    {
      path: "/compatibility/toasts";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/toasts")>;
      $$route?: undefined;
    },
    {
      path: "/(app)/analytics/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/analytics/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/analytics/index")>;
    },
    {
      path: "/(app)/emails/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/index")>;
    },
    {
      path: "/(app)/members/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/index")>;
    },
    {
      path: "/(app)/roles/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/index")>;
    },
    {
      path: "/(app)/roles/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/new")>;
    },
    {
      path: "/(app)/shortlinks/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/index")>;
    },
    {
      path: "/(app)/shortlinks/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/new")>;
    },
    {
      path: "/api/auth/*auth";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/auth/[...auth]")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/auth/[...auth]")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/auth/[...auth]")>;
      $$route?: undefined;
    },
    {
      path: "/members/accept/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/members/accept/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/members/accept/[id]")>;
    },
    {
      path: "/(app)/emails/analytics/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/analytics/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/analytics/index")>;
    },
    {
      path: "/(app)/emails/bounces/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/bounces/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/bounces/index")>;
    },
    {
      path: "/(app)/emails/campaigns/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/[id]")>;
    },
    {
      path: "/(app)/emails/campaigns/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/index")>;
    },
    {
      path: "/(app)/emails/campaigns/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/new")>;
    },
    {
      path: "/(app)/emails/forms/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/forms/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/forms/index")>;
    },
    {
      path: "/(app)/emails/lists/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/[id]")>;
    },
    {
      path: "/(app)/emails/lists/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/index")>;
    },
    {
      path: "/(app)/emails/lists/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/new")>;
    },
    {
      path: "/(app)/emails/subscribers/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/[id]")>;
    },
    {
      path: "/(app)/emails/subscribers/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/index")>;
    },
    {
      path: "/(app)/emails/subscribers/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/new")>;
    },
    {
      path: "/(app)/emails/templates/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/templates/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/templates/[id]")>;
    },
    {
      path: "/(app)/emails/templates/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/templates/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/templates/new")>;
    },
    {
      path: "/(app)/members/:id/roles";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/[id]/roles")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/[id]/roles")>;
    },
    {
      path: "/(app)/members/invitations/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/invitations/new")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/invitations/new")>;
    },
    {
      path: "/(app)/roles/:id/clone";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/[id]/clone")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/[id]/clone")>;
    },
    {
      path: "/(app)/roles/:id/edit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/[id]/edit")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/[id]/edit")>;
    },
    {
      path: "/(app)/shortlinks/:code/details";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/[code]/details")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/[code]/details")>;
    },
    {
      path: "/(app)/shortlinks/:code/edit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/[code]/edit")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/[code]/edit")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/";
      id: "/(app)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(app)")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(app)")>;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/emails";
          id: "/emails";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails")>;
          $$route?: undefined;
          children: readonly [
            {
              path: "/";
              id: "/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/index")>;
              children?: undefined;
            },
            {
              path: "/forms/";
              id: "/forms/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/forms/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/forms/index")>;
              children?: undefined;
            },
            {
              path: "/lists/";
              id: "/lists/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/index")>;
              children?: undefined;
            },
            {
              path: "/bounces/";
              id: "/bounces/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/bounces/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/bounces/index")>;
              children?: undefined;
            },
            {
              path: "/lists/:id";
              id: "/lists/:id";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/[id]")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/[id]")>;
              children?: undefined;
            },
            {
              path: "/lists/new";
              id: "/lists/new";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/lists/new")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/lists/new")>;
              children?: undefined;
            },
            {
              path: "/analytics/";
              id: "/analytics/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/analytics/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/analytics/index")>;
              children?: undefined;
            },
            {
              path: "/campaigns/";
              id: "/campaigns/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/index")>;
              children?: undefined;
            },
            {
              path: "/subscribers/";
              id: "/subscribers/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/index")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/index")>;
              children?: undefined;
            },
            {
              path: "/campaigns/:id";
              id: "/campaigns/:id";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/[id]")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/[id]")>;
              children?: undefined;
            },
            {
              path: "/campaigns/new";
              id: "/campaigns/new";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/campaigns/new")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/campaigns/new")>;
              children?: undefined;
            },
            {
              path: "/templates/:id";
              id: "/templates/:id";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/templates/[id]")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/templates/[id]")>;
              children?: undefined;
            },
            {
              path: "/templates/new";
              id: "/templates/new";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/templates/new")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/templates/new")>;
              children?: undefined;
            },
            {
              path: "/subscribers/:id";
              id: "/subscribers/:id";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/[id]")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/[id]")>;
              children?: undefined;
            },
            {
              path: "/subscribers/new";
              id: "/subscribers/new";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/(app)/emails/subscribers/new")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/emails/subscribers/new")>;
              children?: undefined;
            }
          ];
        },
        {
          path: "/roles/";
          id: "/roles/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/index")>;
          children?: undefined;
        },
        {
          path: "/members/";
          id: "/members/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/index")>;
          children?: undefined;
        },
        {
          path: "/roles/new";
          id: "/roles/new";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/new")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/new")>;
          children?: undefined;
        },
        {
          path: "/analytics/";
          id: "/analytics/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/analytics/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/analytics/index")>;
          children?: undefined;
        },
        {
          path: "/shortlinks/";
          id: "/shortlinks/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/index")>;
          children?: undefined;
        },
        {
          path: "/shortlinks/new";
          id: "/shortlinks/new";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/new")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/new")>;
          children?: undefined;
        },
        {
          path: "/roles/:id/edit";
          id: "/roles/:id/edit";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/[id]/edit")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/[id]/edit")>;
          children?: undefined;
        },
        {
          path: "/roles/:id/clone";
          id: "/roles/:id/clone";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/roles/[id]/clone")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/roles/[id]/clone")>;
          children?: undefined;
        },
        {
          path: "/members/:id/roles";
          id: "/members/:id/roles";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/[id]/roles")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/[id]/roles")>;
          children?: undefined;
        },
        {
          path: "/shortlinks/:code/edit";
          id: "/shortlinks/:code/edit";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/[code]/edit")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/[code]/edit")>;
          children?: undefined;
        },
        {
          path: "/members/invitations/new";
          id: "/members/invitations/new";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/members/invitations/new")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/members/invitations/new")>;
          children?: undefined;
        },
        {
          path: "/shortlinks/:code/details";
          id: "/shortlinks/:code/details";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(app)/shortlinks/[code]/details")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(app)/shortlinks/[code]/details")>;
          children?: undefined;
        }
      ];
    },
    {
      path: "/";
      id: "/(auth)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)")>;
      children: readonly [
        {
          path: "/login";
          id: "/login";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/login")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/reset-password";
          id: "/reset-password";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/reset-password")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/forgot-password";
          id: "/forgot-password";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/forgot-password")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/compatibility/";
      id: "/compatibility/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/compatibility/index")>;
      children?: undefined;
    },
    {
      path: "/compatibility/auth";
      id: "/compatibility/auth";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/auth")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/members/accept/:id";
      id: "/members/accept/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/members/accept/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/members/accept/[id]")>;
      children?: undefined;
    },
    {
      path: "/compatibility/icons";
      id: "/compatibility/icons";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/icons")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/compatibility/toasts";
      id: "/compatibility/toasts";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/toasts")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/compatibility/content";
      id: "/compatibility/content";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/compatibility/content")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
