// Generated by @solidjs/vite-plugin (start.env) — do not edit.
// Regenerated on every dev server and build start from env.ts.
// Keep this file (and the schema) inside your tsconfig "include".

declare module 'virtual:env/client' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "VITE_ADMIN_V2_TITLE": __Out<__Schema["client"]["VITE_ADMIN_V2_TITLE"]>;
  };
  export { env };
  export default env;
}

declare module 'virtual:env/server' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "ADMIN_V2_RUNTIME": __Out<__Schema["server"]["ADMIN_V2_RUNTIME"]>;
    readonly "DATABASE_URL": __Out<__Schema["server"]["DATABASE_URL"]>;
    readonly "BETTER_AUTH_SECRET": __Out<__Schema["server"]["BETTER_AUTH_SECRET"]>;
    readonly "BETTER_AUTH_URL": __Out<__Schema["server"]["BETTER_AUTH_URL"]>;
    readonly "PUBLIC_SITE_URL": __Out<__Schema["server"]["PUBLIC_SITE_URL"]>;
    readonly "LISTMONK_URL": __Out<__Schema["server"]["LISTMONK_URL"]>;
    readonly "LISTMONK_API_TOKEN": __Out<__Schema["server"]["LISTMONK_API_TOKEN"]>;
    readonly "LISTMONK_ADMIN_ACCESS_TEMPLATE_ID": __Out<__Schema["server"]["LISTMONK_ADMIN_ACCESS_TEMPLATE_ID"]>;
    readonly "LISTMONK_INVITATION_TEMPLATE_ID": __Out<__Schema["server"]["LISTMONK_INVITATION_TEMPLATE_ID"]>;
    readonly "LISTMONK_PASSWORD_RESET_TEMPLATE_ID": __Out<__Schema["server"]["LISTMONK_PASSWORD_RESET_TEMPLATE_ID"]>;
    readonly "SHLINK_URL": __Out<__Schema["server"]["SHLINK_URL"]>;
    readonly "SHLINK_API_KEY": __Out<__Schema["server"]["SHLINK_API_KEY"]>;
    readonly "UMAMI_URL": __Out<__Schema["server"]["UMAMI_URL"]>;
    readonly "UMAMI_USERNAME": __Out<__Schema["server"]["UMAMI_USERNAME"]>;
    readonly "UMAMI_PASSWORD": __Out<__Schema["server"]["UMAMI_PASSWORD"]>;
    readonly "UMAMI_WEBSITE_ID": __Out<__Schema["server"]["UMAMI_WEBSITE_ID"]>;
    readonly "VITE_ADMIN_V2_TITLE": __Out<__Schema["client"]["VITE_ADMIN_V2_TITLE"]>;
  };
  export { env };
  export default env;
}
